---
title: Young Fatigue
description: New Single ‘Dislocation‘ Out Now!
image: icon.png

images:
  - DSC03442.jpg
  - DSC03684.jpg
  - IMG_0709.jpg
  - IMG_0712.jpg
  - IMG_0698.jpg
links:
  - title: Bandcamp
    url: https://youngfatigue.bandcamp.com/
  - title: Instagram
    url: https://www.instagram.com/youngfatigue/
  - title: Facebook
    url: https://www.facebook.com/YoungFatigue
  - title: Twitter
    url: https://twitter.com/YoungFatigue
  - title: SoundCloud
    url: https://soundcloud.com/youngfatigue
  - title: YouTube
    url: https://www.youtube.com/channel/UCfAGdI0HuS7C6J1m7_xwARQ
  - title: TikTok
    url: https://www.tiktok.com/@ashdixonmusic
quotes:
  - text: It’s actually really good… really good.
    author: Jeremy Vine, BBC Radio 2
  - text: "[Dislocation] is super fun!"
    author: Elise Cobain, Amazon Music
  - text: Young Fatigue was the band I didn't know I needed until I heard them
    author: Grace-Elizabeth, Lifeisalemon
  - text: A hugely promising band... well worth keeping an ear out for
    author: Adam Ruane, OnTheHouseMusic
