---
title: Example Page
description: This is just an example!
image: icon.png
rootUrl: https://example.org/

data:
  memes:
    - thisisfine
    - keyboardcat
    - IMG_0709.jpg
    - why am i sitting here watching the OC again
    - anothercat
